%% https://creately.com/guides/class-diagram-relationships/ good reference for the types of arrows
classDiagram
    Classroom "1" o-- "*" Post
    Classroom "1" o-- "*" Assignment


    class Classroom{
      +uuid id
      +String name
      +User createdBy
      +DateTime createdAt
      +List~Assignment~ assignments
      +List~Post~ posts
      +List~Attachment~ attachments

      
      +getId*()
      +getName*()
      +getCreatedBy*()
      +getCreatedAt*()
      +getAssignments*()
      +getPosts*()
      +getAttachments*()
      +getMembers*()
    }

    class Post{
      +uuid Id
      +String title
      +String contents
      +User createdBy
      +DateTime createdAt
      +uuid classroomId
      +List~Attachment~ attachments

      -getId()
      -getTitle()
      -getContents()
      -getCreatedBy()
      -getClassroomId()
      -getAttachments()
    }

    class Assignment {
        +uuid id
        +String name
        +String contents
        +uuid createdBy
        +uuid classroomId
        +dateTime createdAt
        +List~File~ files
        +List~string~ links

        -getId()uuid
        -getContents() String
        -getCreatedBy() uuid
        -getCreatedByUsername() String
        -getClassroomId() uuid
        -getClassroomName() String
        -getCreatedAt() dateTime
        -getFiles() List~File~
    }