classDiagram

    class Classroom{
      +uuid id
      +String name
      +User createdBy
      +DateTime createdAt
      +List<Assignment> assignments
      +List<Post> posts
      +List<Attachment> attachments

      
      +getId*()
      +getName*()
      +getCreatedBy*()
      +getCreatedAt*()
      +getAssignments*()
      +getPosts*()
      +getAttachments*()
      +getMembers*()
    }

    class Post{
      +uuid Id
      +String Title
      +String contents
      +User createdBy
      +DateTime createdAt
      +uuid classroomId
      +List<Attachment> attachments

      -getId()
      -getTitle()
      -getContents()1
      -getCreatedBy()
      -getClassroomId()
      -getAttachments()
    }

    class Assignment {
        +uuid id
        +string name
        +uuid createdBy
        +uuid classroomId
        +dateTime createdAt
        +List<File> files
    }