    erDiagram

        User {
            uuid subjectId PK
            uuid profilePicture FK
        }
  


        %% CLASSROOM

        Classroom {
            uuid id PK
            string name
            uuid createdBy
            DateTime createdAt
            uuid assignments FK
            uuid posts FK
            uuid chatId FK
            uuid attachments
        }
        Classroom ||--o{ User : contains
        User ||--o{ Classroom : creates
        Classroom ||--o{ Classroom_MEMBERS : creates
        
        Classroom_MEMBERS ||--o{ User : contains
        Classroom_MEMBERS {
            uuid userId PK
            uuid ClassroomId FK
        }


        %% ASSIGNMENT

        Classroom ||--o{ Assignment : contains
        Assignment ||--o{ File : contains
        Assignment ||--o{ User : contains
        Assignment {
            uuid id PK
            string name
            string contents
            uuid createdBy
            uuid classroomId FK
            DateTime createdAt
            uuid files FK
        }
        User ||--o{  SUBMITTED_ASSIGNMENT : creates
        SUBMITTED_ASSIGNMENT {
            uuid assignmentId
            uuid userId
            datetime submittedAt
        }
        SUBMITTED_ASSIGNMENT_ATTACHMENTS ||--o{ SUBMITTED_ASSIGNMENT : contains
        SUBMITTED_ASSIGNMENT_ATTACHMENTS {
            uuid submittedAssignmentId FK
            uuid fileId FK
        }

        Classroom ||--o{ Post : contains
        Post ||--o{ File : contains
        Post ||--o{ User : contains


        Post {
            uuid id PK
            string title
            string contents
            uuid createdBy
            DateTime createdAt
            uuid ClassroomId FK
            uuid attachments
        }



        %% FILE

        File ||--o{ User : contains
        File {
            uuid id PK
            string name
            string mimetype
            DateTime createdAt
            uuid Classroom FK
            uuid owner
            uuid sharedWith
            string key
            bool systemFile
        }


        %% URL

        Post ||--o{ Url : contains
        Assignment ||--o{ Url : contains
        Url {
            uuid id PK
            string url
            string title
        }


        %% CHAT

        Chat ||--o{ CHAT_MEMBERS : creates
        Chat ||--o{ User : contains
        User ||--o{ Chat : creates
        Chat ||--o{ CHAT_MESSAGES : contains
        Chat {
            uuid id PK
            string name
            datetime createdAt
            uuid createdBy FK
        }

        CHAT_MEMBERS ||--o{ User : "is"
        CHAT_MEMBERS {
            uuid chatId FK
            uuid userId FK
        }

        CHAT_MESSAGES {
            uuid id
            uuid sentBy
            uuid sentTo
            uuid contents
            datetime sentAt
        }

        CHAT_MESSAGES ||--o{ CHAT_MESSAGE_ATTACHMENTS : contains
        CHAT_MESSAGE_ATTACHMENTS ||--o{ File : contains
        CHAT_MESSAGE_ATTACHMENTS {
            uuid messageId
            uuid fileId

        }



        %% QUESTIONS/QUIZ

        QUIZ ||--|{  QUESTION_TEXT : contains
        QUESTION_TEXT {
            uuid id PK
            uuid quizId FK
            string title
            string answer
        }
        QUESTION_TEXT ||--|{  QUESTION_TEXT_ANSWER : contains
        User ||--|{  QUESTION_TEXT_ANSWER : creates
        QUESTION_TEXT_ANSWER {
            uuid belongsTo FK
            string answer
        }

        QUIZ ||--|{  QUESTION_RADIO : contains
        QUESTION_RADIO {
            uuid id PK
            uuid quizId FK
            string title
        }
        QUESTION_RADIO ||--|{  QUESTION_RADIO_OPTIONS : contains
        QUESTION_RADIO_OPTIONS {
            uuid id PK
            uuid radioId FK
            string title
            bool answer
        }
        User ||--o{ QUESTION_RADIO_ANSWER : creates
        QUESTION_RADIO_ANSWER ||--o{ QUESTION_RADIO : contains
        QUESTION_RADIO_ANSWER ||--o{ QUESTION_RADIO_OPTIONS : contains
        QUESTION_RADIO_ANSWER {
            uuid answerTo FK
            uuid createdBy FK
            uuid option FK
        }


        QUIZ ||--|{  QUESTION_CHECKBOX : contains
        QUESTION_CHECKBOX {
            uuid id PK
            uuid quizId FK
            string title
        }
        QUESTION_CHECKBOX ||--|{  QUESTION_CHECKBOX_OPTIONS : contains
        QUESTION_CHECKBOX_OPTIONS {
            uuid id PK
            uuid quizId FK
            string name
            bool answer
        }
        QUESTION_CHECKBOX_ANSWER ||--|{  QUESTION_CHECKBOX_OPTIONS : contains
        QUESTION_CHECKBOX_ANSWER ||--|{  QUESTION_CHECKBOX_OPTIONS : contains
        QUESTION_CHECKBOX_ANSWER ||--|{  User : contains
        User ||--|{  QUESTION_CHECKBOX_ANSWER : creates
        QUESTION_CHECKBOX_ANSWER {
            uuid selected FK
            uuid createdBy FK
            uuid questionId FK
        }

        QUIZ ||--|{  QUESTION_PAIRS : contains
        QUESTION_PAIRS {
            uuid id PK
            uuid quizId FK
            string title
        }
        QUIZ ||--|{  QUESTION_PAIRS : contains
        QUESTION_PAIRS ||--|{  QUESTION_PAIRS_PAIR : contains
        QUESTION_PAIRS_PAIR ||--|{   QUESTION_PAIR_OPTIONS: contains
        QUESTION_PAIRS_PAIR {
            uuid questionPairId FK
            uuid left FK
            uuid right FK
        }

        QUESTION_PAIR_OPTIONS ||--|{   QUESTION_PAIRS : contains
        QUESTION_PAIR_OPTIONS {
            uuid id PK
            uuid belongsTo FK
            string contents
        }

        User ||--|{   QUESTION_PAIRS_ANSWER: creates
        QUESTION_PAIRS_ANSWER ||--|{   User: contains
        QUESTION_PAIRS_ANSWER ||--|{   QUESTION_PAIR_OPTIONS: contains
        QUESTION_PAIRS_ANSWER ||--|{   QUESTION_PAIRS: contains
        QUESTION_PAIRS_ANSWER {
            uuid questionPairId FK
            uuid createdBy FK
            uuid left FK
            uuid right FK
        }

        QUIZ ||--|{  QUESTION_ORDER : contains
        QUESTION_ORDER {
            uuid id PK
            uuid quizId FK
            string title
        }
        QUESTION_ORDER_ANSWER ||--|{  QUESTION_ORDER_OPTIONS : contains
        User ||--|{  QUESTION_ORDER_ANSWER : creates
        QUESTION_ORDER_ANSWER {
            uuid optionId FK
            int place
            uuid createdBy FK
        }

        QUESTION_ORDER ||--|{  QUESTION_ORDER_OPTIONS : contains
        QUESTION_ORDER_OPTIONS {
            uuid id PK
            uuid orderId FK
            string title
            int place "1...3"
        }

        QUIZ ||--|{  QUESTION_FILE : contains
        QUESTION_FILE ||--|{  File : contains
        QUESTION_FILE {
            uuid id PK
            uuid quizId FK
            string title
            uuid fileId FK
        }
        User ||--o{ QUESTION_FILE_ANSWER : creates
        QUESTION_FILE_ANSWER ||--o{ QUESTION_FILE : contains
        QUESTION_FILE_ANSWER ||--o{ File : contains
        QUESTION_FILE_ANSWER {
            uuid answerTo FK
            uuid createdBy FK
            uuid fileId FK
        }

     
        User ||--o{ QUIZ : creates
        QUIZ ||--o{ User : contains
        QUIZ {
            uuid id PK
            string name
            uuid createdBy FK
            datetime createdAt
        }