    erDiagram

        User {
            uuid subjectId PK
            uuid profilePicture FK
        }
  

        %% 
        %% CLASSROOM
        %% 
        Classroom {
            uuid id PK
            string name
            uuid createdBy FK
            string joinCode
            DateTime createdAt
            uuid chatId FK
        }

        
        Classroom_MEMBERS {
            uuid userId PK
            uuid ClassroomId FK
        }
        CLASSROOM_ATTACHMENTS {
            uuid fileId fk
            uuid classroomId FK
            datetime attachedAt
            %% topic?
            string topic
        }
        CLASSROOM_ASSIGNMENTS {
            uuid assignmentId FK
            uuid belongTo FK
            uuid createdBy FK
        }



        %% 
        %% ASSIGNMENT
        %% 
        Assignment {
            uuid id PK
            string name
            string contents
            uuid createdBy
            uuid classroomId FK
            DateTime createdAt
            uuid files FK
        }

        SUBMITTED_ASIGNMENT {
            uuid assignmentId
            uuid userId
            datetime submittedAt
        }
        SUBMITTED_ASIGNMENT_ATTACHMENTS {
            uuid submittedAssignmentId FK
            uuid fileId FK
        }

        %% A table that contains all the comments made under an assignment these are public to everyone
        ASSIGNMENT_COMMENT {
            uuid belongsTo FK
            uuid userId FK
            datetime createdAt

        }

        Post {
            uuid id PK
            string title
            %% markdown contents
            string contents
            uuid createdBy
            DateTime createdAt
            %% which classroom does the post belong to
            uuid belongsTo FK
            uuid attachments
        }


        %% 
        %% FILE
        %% 
        File {
            uuid id PK
            string name
            string mimetype
            datetime createdAt
            datetime updatedAt
            uuid Classroom FK
            uuid owner
            uuid sharedWith
            string key
            %% if user attaches it to a quiz or assignment the system locks the file so it cannot be edited after submission
            bool locked 
            bool systemFile
        }

        %% 
        %% CHAT
        %% 
        Chat {
            uuid id PK
            string name
            datetime createdAt
            uuid createdBy FK
        }

        CHAT_MEMBERS {
            uuid chatId FK
            uuid userId FK
        }

        CHAT_MESSAGES {
            uuid id
            uuid sentBy
            uuid sentTo
            uuid contents
            datetime sentAt
        }

        CHAT_MESSAGE_ATTACHMENTS {
            uuid messageId
            uuid fileId

        }


        %% 
        %% QUESTIONS/QUIZ
        %% 
        QUESTION_TEXT {
            uuid id PK
            uuid quizId FK
            string title
            string answer
        }
        QUESTION_TEXT_ANSWER {
            uuid belongsTo FK
            string answer
            uuid createdBy FK
        }
   

        QUESTION_RADIO {
            uuid id PK
            uuid quizId FK
            string title
        }
        QUESTION_RADIO_OPTIONS {
            uuid id PK
            uuid radioId FK
            string title
            bool answer
        }
        QUESTION_RADIO_ANSWER {
            %% The quiz question this answer is replyting to
            uuid answerTo FK
            %% user.id
            uuid createdBy FK
            %% option selected by the user (question_radio_options.id)
            uuid selectedId FK

        }


        QUESTION_CHECKBOX {
            uuid id PK
            uuid quizId FK
            string title
        }
        QUESTION_CHECKBOX_OPTIONS {
            uuid id PK
            uuid belongsTo FK
            string name
            bool answer
        }
        QUESTION_CHECKBOX_ANSWER {
            %% selected = question_checkbox_options.id
            uuid selectedId FK
            %% user.id
            uuid createdBy FK
            %% question_checkbox.id
            uuid questionId FK
        }

        QUESTION_PAIR_COLLECTION {
            uuid id PK
            uuid quizId FK
            string title
        }
        QUESTION_PAIR_COLLECTION_PAIR {
            uuid questionPairId FK
            uuid left FK
            uuid right FK
        }

        QUESTION_PAIR_OPTIONS {
            uuid id PK
            uuid belongsTo FK
            string contents
        }

        QUESTION_PAIR_COLLECTION_ANSWER {
            uuid questionPairId FK
            uuid createdBy FK
            uuid left FK
            uuid right FK
        }

        QUESTION_ORDER {
            uuid id PK
            uuid quizId FK
            string title
        }
        QUESTION_ORDER_ANSWER {
            uuid optionId FK
            int place
            uuid createdBy FK
        }

        QUESTION_ORDER_OPTIONS {
            uuid id PK
            uuid orderId FK
            string title
            int place "1...3"
        }

        QUESTION_FILE {
            uuid id PK
            uuid quizId FK
            string title
            uuid fileId FK
        }
        QUESTION_FILE_ANSWER {
            uuid answerTo FK
            uuid createdBy FK
            uuid fileId FK
        }

     
        QUIZ {
            uuid id PK
            string name
            uuid createdBy FK
            datetime createdAt
            datetime deadline
            %% whether the user can view the results after they have submitted it
            %% false = only can view if everyone has finished i t
            bool viewAfterSubmittion
        }
        %% TODO comments for post
        %% TODO groups for assignments
        %% TODO chat for assignment groups
        