gantt
    title Gantt diagram for the whole project
    dateFormat YYYY-MM-DD
    section design
        Basic ERD diagram :2024-09-02, 14d
    section frontend
        asd :f1, 2024-09-09, 213d
        nasd :after f1,20d
    section backend

    section database
