server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    registryFetchIntervalSeconds: ${REFRESH_INTERVAL:30}
    service-url:
      defaultZone: http://localhost:8761/eureka

  instance:
    hostname: localhost

spring:
  application:
    name: eureka
  security:
    # TODO remove after testing
    user:
      name: admin
      password: admin

logging:
  file:
    name: ././logs/eureka.log