name: Mirror dev branch to remote

on:
  push:
    branches: ["master"]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone bare dev branch
        run: git clone --bare https://git.4o1x5.dev/${{ github.repository }} -b master
      - name: Mirror to github
        run: |
         cd learningpulse.git && \
         git push --mirror https://nezsha:${{ secrets.MIRROR_USER_PASSWORD }}@github.com/nezsha/lp.git



