server:
  port: 0

spring:
  application:
    name: drive
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://${DB_URL}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  # TODO remove after testing
#  security:
#    user:
#      name: admin
#      password: admin

springdoc:
  api-docs:
    enabled: true
    path: /api/v1/drive/v3/api-docs
  swagger-ui:
    path: /api/v1/drive/swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  file:
    name: ././logs/drive.log