server:
  port: 0

spring:
  application:
    name: quiz

springdoc:
  api-docs:
    enabled: true
    path: /api/v1/quiz/v3/api-docs
  swagger-ui:
    path: /api/v1/quiz/swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  file:
    name: ././logs/quiz.log