networks:
  learningpulse: {}
services:
  eureka:
    image: git.4o1x5.dev/learningpulse/server/eureka:dev
    restart: always
    hostname: eureka-server
    ports:
      - 8761:8761
    networks:
      - learningpulse
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  # to test
  # curl http://admin:admin@localhost:8181/api/v1/dummy/test -v;
  dummy:
    # TODO fix broken image link
    image: git.4o1x5.dev/learningpulse/server/dummy:dev
    restart: always
    depends_on:
      - eureka
    networks:
      - learningpulse
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  gateway:
    # TODO fix broken image link
    image: git.4o1x5.dev/learningpulse/server/gateway:dev
    restart: always
    depends_on:
      - eureka
      - dummy
    ports:
      - 8181:8181
    networks:
      - learningpulse
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  keycloak:
    container_name: keycloak
    hostname: keycloak
    image: quay.io/keycloak/keycloak:latest
    command: ["start-dev", "--import-realm"]
    ports:
      - ${KC_PORT:-8081}:8080
    volumes:
      - ./autoconfig/realms:/opt/keycloak/data/import
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://lp_database:{DB_PORT:- 5432}/${KC_DB_NAME_SCHEMA:- keycloak}
      KC_DB_USERNAME: ${DB_USER:-lp}
      KC_DB_PASSWORD: ${DB_PASSWORD:-lp}
      KC_DB_SCHEMA: ${KC_DB_NAME_SCHEMA:-lp}
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_ENABLED: true
    networks:
      - learningpulse
    depends_on:
      - database

  database:
    container_name: lp_database
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT:- 5432}:5432
    volumes:
      - learning_pulse_pgdata:/var/lib/postgresql/data
      - ./autoconfig/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    networks:
      - learningpulse

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    ports:
      - "${PG_ADMIN_PORT:-8888}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_USERNAME: admin
      PGADMIN_DEFAULT_PASSWORD: root
    volumes:
      - learning_pulse_pgadmin:/var/lib/pgadmin
    networks:
      - learningpulse

volumes:
  learning_pulse_pgdata:
  learning_pulse_pgadmin:
  realms:
