networks:
  learningpulse: {}
services:
  eureka:
    image: git.4o1x5.dev/learningpulse/server/eureka:dev
    restart: always
    hostname: eureka-server
    ports:
      - 8761:8761
    networks:
      - learningpulse
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  # to test
  # curl http://admin:admin@localhost:8181/api/v1/dummy/test -v;
  dummy:
    # TODO fix broken image link
    image: git.4o1x5.dev/learningpulse/server/dummy:dev
    restart: always
    depends_on:
      - eureka
    networks:
      - learningpulse
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  gateway:
    # TODO fix broken image link
    image: git.4o1x5.dev/learningpulse/server/gateway:dev
    restart: always
    depends_on:
      - eureka
      - dummy
    ports:
      - 8181:8181
    networks:
      - learningpulse
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  keycloak:
    container_name: keycloak
    hostname: keycloak
    image: quay.io/keycloak/keycloak:latest
    command: ["start-dev", "--import-realm"]
    ports:
      - ${KC_PORT}:8080
    volumes:
      - realms:/opt/keycloak/data/import
    environment:
      KC_DB: postgres
      # Do not remove the environment variables below, cus
      # how else are you going to develop the gateway service,
      # if not running it locally
      KC_DB_URL: jdbc:postgresql://${DB_URL}:${DB_PORT}/${KC_DB_NAME_SCHEMA}
      KC_DB_USERNAME: ${DB_USER}
      KC_DB_PASSWORD: ${DB_PASSWORD}
      KC_DB_SCHEMA: ${KC_DB_NAME_SCHEMA}
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_ENABLED: true
    networks:
      - learningpulse

  database:
    container_name: lp_database
    image: postgres
    restart: always
    hostname: ${DB_URL}
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - learning_pulse_pgdata:/var/lib/postgresql/data
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    networks:
      - learningpulse

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_USERNAME: admin
      PGADMIN_DEFAULT_PASSWORD: root
    volumes:
      - learning_pulse_pgadmin:/var/lib/pgadmin
    networks:
      - learningpulse

volumes:
  learning_pulse_pgdata:
  learning_pulse_pgadmin:
  realms:
