networks:
  learningpulse: {}
services:
  keycloakdb:
    image: postgres
    restart: unless-stopped
    hostname: keycloakdb
    networks:
      - learningpulse
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "keycloak"]
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    restart: unless-stopped
    command: ["start-dev", "--import-realm"]
    volumes:
      - ./autoconfig/realms:/opt/keycloak/data/import
    depends_on:
      - keycloakdb
    environment:
      KC_DB: postgres
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_DB_URL: "jdbc:postgresql://keycloakdb:5432/keycloak"
      KC_METRICS_ENABLED: false
      KC_REALM_NAME: learningpulse
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - learningpulse
    ports:
      - ${KC_PORT:-8081}:8080

  database:
    hostname: database
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: "lp"
      POSTGRES_PASSWORD: "lp"
    ports:
      - ${DB_PORT:-5432}:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./autoconfig/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    networks:
      - learningpulse

volumes:
  pgdata:
