server:
  port: 8181

spring:
  application:
    name: gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        # eureka service routing
        - id: eureka
          # Will only work when docker is used
          # uri: http://${app.eureka-server}:8761
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/
        - id: eureka-static
          # Will only work when docker is used
          # uri: http://${app.eureka-server}:8761
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**

        ########### Service routing ###########

        # dummy service routing
        - id: dummy
          uri: lb://dummy
          predicates:
            - Path=/api/v1/dummy/**
          filters:
            - AddResponseHeader=X-Powered-By, LearningPulse Gateway Service
        # user service routing
        - id: user
          uri: lb://user
          predicates:
            - Path=/api/v1/user/**
          filters:
            - AddResponseHeader=X-Powered-By, LearningPulse Gateway Service
        # quiz service routing
        - id: quiz
          uri: lb://quiz
          predicates:
            - Path=/api/v1/quiz/**
          filters:
            - AddResponseHeader=X-Powered-By, LearningPulse Gateway Service
        # drive service routing
        - id: file
          uri: lb://drive
          predicates:
            - Path=/api/v1/drive/**
          filters:
            - AddResponseHeader=X-Powered-By, LearningPulse Gateway Service
        # classroom service
        - id: classroom
          uri: lb://classroom
          predicates:
            - Path=/api/v1/classroom/**
          filters:
            - AddResponseHeader=X-Powered-By, LearningPulse Gateway Service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KC_ISSUER_URI:- http://localhost:8081/auth/realms/learning_pulse}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true

springdoc:
  api-docs:
    enabled: true
    groups:
      enabled: true
  swagger-ui:
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - name: Gateway API
        url: /v3/api-docs
      - name: Dummy Service API
        url: /api/v1/dummy/v3/api-docs
      - name: User Service API
        url: /api/v1/user/v3/api-docs
      - name: Quiz Service API
        url: /api/v1/quiz/v3/api-docs
      - name: File Service API
        url: /api/v1/file/v3/api-docs

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:- http://localhost:8761/eureka}
      # Will only work when docker is used
#      defaultZone: http://eureka-server:8761/eureka

logging:
  file:
    name: ././logs/gateway.log
