server:
  port: 0

spring:
  application:
    name: user
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

springdoc:
  api-docs:
    enabled: true
    path: /api/v1/user/v3/api-docs
  swagger-ui:
    path: /api/v1/user/swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  file:
    name: ././logs/user.log