server:
  port: 0

spring:
  application:
    name: dummy

  # TODO remove after testing
  security:
    user:
      name: admin
      password: admin

springdoc:
  api-docs:
    enabled: true
    path: /api/v1/dummy/v3/api-docs
  swagger-ui:
    path: /api/v1/dummy/swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  file:
    name: ././logs/dummy.log